Modular questions on front-end
Watts-Lab/commonsense-platform pull request #106
Opened 2024-01-11 00:06 UTC by amirrr

## Describe your changes

1. Removed console.logs from production
2. Questions now load from JSON
3. Manifest.js only serves two treatments in two design spaces with only the cleaned statements

## Issue ticket number and link

2024-01-11 00:26 UTC, amirrr commented on client/src/components/Enter.tsx
Now after login user redirect to dashboard

2024-01-11 01:34 UTC, amirrr commented on server/survey/manifest.js
Only do 2 treaments

2024-01-13 15:03 UTC, markwhiting requested changes
Overall looks good but a few questions.

2024-01-13 15:03 UTC, markwhiting commented on server/survey/manifest.js
This looks like it’s hard coded for Duncan?

2024-01-13 15:03 UTC, markwhiting commented on server/survey/treatments/design-point.ts
We can probably do this as weighted exploration over an array of constant design points that we modify over time. So when we add more they become the focal ones.

2024-01-13 15:03 UTC, markwhiting commented on client/src/components/QuestionOne.tsx
Not sure how this is used. Is it needed if we are using the file driven method?

2024-01-17 02:57 UTC, markwhiting approved these changes
Made some new issues but I think this looks good to go for now!

2024-01-17 02:57 UTC, markwhiting commented on client/src/components/MultiStepForm.tsx
>            I_agree_reason:
I'll create an issue for removing hard coding of variable names around this.

2024-01-17 02:57 UTC, markwhiting commented on client/src/components/MultiStepForm.tsx
>            I_agree_reason:
(as in, we need not fix it now, but should in a next cycle)

2024-01-17 07:48 UTC, merged